import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
   theme: {
    extend: {
      fontFamily: {
      sans: ["var(--font-inter)", "Inter", "sans-serif"],
     },
      fontSize: {
        // Display
        "display-1": ["var(--font-size-display-1)", { lineHeight: "var(--line-height-display-1)" }],
        "display-2": ["var(--font-size-display-2)", { lineHeight: "var(--line-height-display-2)" }],
        "display-3": ["var(--font-size-display-3)", { lineHeight: "var(--line-height-display-3)" }],
        "display-4": ["var(--font-size-display-4)", { lineHeight: "var(--line-height-display-4)" }],
        "display-5": ["var(--font-size-display-5)", { lineHeight: "var(--line-height-display-5)" }],
  
        // Heading
        h1: ["var(--font-size-h1)", { lineHeight: "var(--line-height-h1)" }],
        h2: ["var(--font-size-h2)", { lineHeight: "var(--line-height-h2)" }],
        h3: ["var(--font-size-h3)", { lineHeight: "var(--line-height-h3)" }],
        h4: ["var(--font-size-h4)", { lineHeight: "var(--line-height-h4)" }],
        h5: ["var(--font-size-h5)", { lineHeight: "var(--line-height-h5)" }],
        h6: ["var(--font-size-h6)", { lineHeight: "var(--line-height-h6)" }],
  
        // Body
        "body-lg": ["var(--font-size-body-lg)", { lineHeight: "var(--line-height-body-lg)" }],
        "body-md": ["var(--font-size-body-md)", { lineHeight: "var(--line-height-body-md)" }],
        "body-sm": ["var(--font-size-body-sm)", { lineHeight: "var(--line-height-body-sm)" }],
        "body-xs": ["var(--font-size-body-xs)", { lineHeight: "var(--line-height-body-xs)" }],
        "body-xxs": ["var(--font-size-body-xxs)", { lineHeight: "var(--line-height-body-xxs)" }],
      },
      colors: {
        // Base
        base: {
          white: "var(--color-base-white)",
          "grey-light": "var(--color-base-grey-light)",
          tertiary: "var(--color-base-tertiary)",
          dark: "var(--color-base-dark)",
          black: "var(--color-base-black)",
        },
 
        // Typography
        text: {
          black: "var(--color-text-black)",
          white: "var(--color-text-white)",
          subtitle: "var(--color-text-subtitle)",
          placeholder: "var(--color-text-placeholder)",
          disabled: "var(--color-text-disabled)",
        },
 
        // Neutral
        gray: {
          50: "var(--color-gray-50)",
          100: "var(--color-gray-100)",
          200: "var(--color-gray-200)",
          300: "var(--color-gray-300)",
          400: "var(--color-gray-400)",
          500: "var(--color-gray-500)",
          600: "var(--color-gray-600)",
          700: "var(--color-gray-700)",
          800: "var(--color-gray-800)",
          900: "var(--color-gray-900)",
          950: "var(--color-gray-950)",
          1000: "var(--color-gray-1000)",
        },
 
        // Functional
        error: {
          50: "var(--color-error-50)",
          100: "var(--color-error-100)",
          200: "var(--color-error-200)",
          300: "var(--color-error-300)",
          400: "var(--color-error-400)",
          500: "var(--color-error-500)",
          600: "var(--color-error-600)",
          700: "var(--color-error-700)",
          800: "var(--color-error-800)",
          900: "var(--color-error-900)",
          950: "var(--color-error-950)",
          1000: "var(--color-error-1000)",
        },
        info: {
          50: "var(--color-info-50)",
          100: "var(--color-info-100)",
          200: "var(--color-info-200)",
          300: "var(--color-info-300)",
          400: "var(--color-info-400)",
          500: "var(--color-info-500)",
          600: "var(--color-info-600)",
          700: "var(--color-info-700)",
          800: "var(--color-info-800)",
          900: "var(--color-info-900)",
          950: "var(--color-info-950)",
          1000: "var(--color-info-1000)",
        },
        success: {
          50: "var(--color-success-50)",
          100: "var(--color-success-100)",
          200: "var(--color-success-200)",
          300: "var(--color-success-300)",
          400: "var(--color-success-400)",
          500: "var(--color-success-500)",
          600: "var(--color-success-600)",
          700: "var(--color-success-700)",
          800: "var(--color-success-800)",
          900: "var(--color-success-900)",
          950: "var(--color-success-950)",
          1000: "var(--color-success-1000)",
        },
        warning: {
          50: "var(--color-warning-50)",
          100: "var(--color-warning-100)",
          200: "var(--color-warning-200)",
          300: "var(--color-warning-300)",
          400: "var(--color-warning-400)",
          500: "var(--color-warning-500)",
          600: "var(--color-warning-600)",
          700: "var(--color-warning-700)",
          800: "var(--color-warning-800)",
          900: "var(--color-warning-900)",
          950: "var(--color-warning-950)",
          1000: "var(--color-warning-1000)",
        },
 
        // Primary
        primary: {
          50: "var(--color-primary-50)",
          100: "var(--color-primary-100)",
          200: "var(--color-primary-200)",
          300: "var(--color-primary-300)",
          400: "var(--color-primary-400)",
          500: "var(--color-primary-500)",
          600: "var(--color-primary-600)",
          700: "var(--color-primary-700)",
          800: "var(--color-primary-800)",
          900: "var(--color-primary-900)",
          950: "var(--color-primary-950)",
        },
 
        // Secondary (⚠️ placeholder values — see tokens.css TODO)
        secondary: {
          50: "var(--color-secondary-50)",
          100: "var(--color-secondary-100)",
          200: "var(--color-secondary-200)",
          300: "var(--color-secondary-300)",
          400: "var(--color-secondary-400)",
          500: "var(--color-secondary-500)",
          600: "var(--color-secondary-600)",
          700: "var(--color-secondary-700)",
          800: "var(--color-secondary-800)",
          900: "var(--color-secondary-900)",
          950: "var(--color-secondary-950)",
        },
 
        // Tertiary palettes
        "tertiary-green": {
          50: "var(--color-tertiary-green-50)",
          100: "var(--color-tertiary-green-100)",
          200: "var(--color-tertiary-green-200)",
          300: "var(--color-tertiary-green-300)",
          400: "var(--color-tertiary-green-400)",
          500: "var(--color-tertiary-green-500)",
          600: "var(--color-tertiary-green-600)",
          700: "var(--color-tertiary-green-700)",
          800: "var(--color-tertiary-green-800)",
          900: "var(--color-tertiary-green-900)",
          950: "var(--color-tertiary-green-950)",
        },
        "tertiary-black": {
          50: "var(--color-tertiary-black-50)",
          100: "var(--color-tertiary-black-100)",
          200: "var(--color-tertiary-black-200)",
          300: "var(--color-tertiary-black-300)",
          400: "var(--color-tertiary-black-400)",
          500: "var(--color-tertiary-black-500)",
          600: "var(--color-tertiary-black-600)",
          700: "var(--color-tertiary-black-700)",
          800: "var(--color-tertiary-black-800)",
          900: "var(--color-tertiary-black-900)",
          950: "var(--color-tertiary-black-950)",
        },
        "tertiary-purple": {
          50: "var(--color-tertiary-purple-50)",
          100: "var(--color-tertiary-purple-100)",
          200: "var(--color-tertiary-purple-200)",
          300: "var(--color-tertiary-purple-300)",
          400: "var(--color-tertiary-purple-400)",
          500: "var(--color-tertiary-purple-500)",
          600: "var(--color-tertiary-purple-600)",
          700: "var(--color-tertiary-purple-700)",
          800: "var(--color-tertiary-purple-800)",
          900: "var(--color-tertiary-purple-900)",
          950: "var(--color-tertiary-purple-950)",
        },
        "tertiary-orange": {
          50: "var(--color-tertiary-orange-50)",
          100: "var(--color-tertiary-orange-100)",
          200: "var(--color-tertiary-orange-200)",
          300: "var(--color-tertiary-orange-300)",
          400: "var(--color-tertiary-orange-400)",
          500: "var(--color-tertiary-orange-500)",
          600: "var(--color-tertiary-orange-600)",
          700: "var(--color-tertiary-orange-700)",
          800: "var(--color-tertiary-orange-800)",
          900: "var(--color-tertiary-orange-900)",
          950: "var(--color-tertiary-orange-950)",
        },
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
